services:
  protected-server:
    build: ./protected-server
    container_name: protected-server
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TRUSTED_IP=172.28.0.20
    networks:
      labnet:
        ipv4_address: 172.28.0.10
    ports:
      - "8080:80"

  client-trusted:
    image: nicolaka/netshoot:latest
    container_name: client-trusted
    command: sleep infinity
    networks:
      labnet:
        ipv4_address: 172.28.0.20

  client-blocked:
    image: nicolaka/netshoot:latest
    container_name: client-blocked
    command: sleep infinity
    networks:
      labnet:
        ipv4_address: 172.28.0.30

networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
